<a href="https://colab.research.google.com/github/Ramyanee/nlp_preprocessing/blob/master/nlp_text_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
tf.__version__


'2.2.0-rc4'

In [0]:
from tensorflow.keras.preprocessing.text import Tokenizer as tk

In [0]:
from tensorflow.keras.preprocessing.sequence import pad_sequences as pd_sq

In [0]:
sentences = [
             "i love mountains and breeze.",
             "i am going to be awesome.",
             "i was born awesome."
]

In [0]:
MAX_VOCAB_SIZE = 20000

In [0]:
tokenizer = tk(num_words = MAX_VOCAB_SIZE)

In [0]:
tokenizer.fit_on_texts(sentences)

In [0]:
sequences = tokenizer.texts_to_sequences(sentences)

In [0]:
sequences

[[1, 3, 4, 5, 6], [1, 7, 8, 9, 10, 2], [1, 11, 12, 2]]

In [0]:
tokenizer.word_index

{'am': 7,
 'and': 5,
 'awesome': 2,
 'be': 10,
 'born': 12,
 'breeze': 6,
 'going': 8,
 'i': 1,
 'love': 3,
 'mountains': 4,
 'to': 9,
 'was': 11}

In [0]:
data = pd_sq(sequences)

In [0]:
data

array([[ 0,  1,  3,  4,  5,  6],
       [ 1,  7,  8,  9, 10,  2],
       [ 0,  0,  1, 11, 12,  2]], dtype=int32)

In [0]:
MAX_SEQ_LEN = 10

In [0]:
data = pd_sq(sequences, maxlen= MAX_SEQ_LEN)

In [0]:
data

array([[ 0,  0,  0,  0,  0,  1,  3,  4,  5,  6],
       [ 0,  0,  0,  0,  1,  7,  8,  9, 10,  2],
       [ 0,  0,  0,  0,  0,  0,  1, 11, 12,  2]], dtype=int32)

In [0]:
data = pd_sq(sequences, maxlen= MAX_SEQ_LEN, padding = 'post')

In [0]:
data

array([[ 1,  3,  4,  5,  6,  0,  0,  0,  0,  0],
       [ 1,  7,  8,  9, 10,  2,  0,  0,  0,  0],
       [ 1, 11, 12,  2,  0,  0,  0,  0,  0,  0]], dtype=int32)

In [0]:
data = pd_sq(sequences, maxlen= 5)

In [0]:
data

array([[ 1,  3,  4,  5,  6],
       [ 7,  8,  9, 10,  2],
       [ 0,  1, 11, 12,  2]], dtype=int32)

In [0]:
data = pd_sq(sequences, maxlen= 5, truncating = "post")
data

array([[ 1,  3,  4,  5,  6],
       [ 1,  7,  8,  9, 10],
       [ 0,  1, 11, 12,  2]], dtype=int32)